import { DarkTheme, DefaultTheme, type Theme } from "@react-navigation/native";

export const THEME = {
  light: {
    background: "#ffffff",
    foreground: "#0a0a0f",
    card: "#ffffff",
    cardForeground: "#0a0a0f",
    popover: "#ffffff",
    popoverForeground: "#0a0a0f",
    primary: "#5269FF",
    primaryForeground: "#ffffff",
    secondary: "#F3F5FC",
    secondaryForeground: "#1F2A7A",
    muted: "#F4F4F6",
    mutedForeground: "#6F6F7B",
    accent: "#DBE1FF",
    accentForeground: "#4155D8",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#E1E4EF",
    input: "#E1E4EF",
    ring: "#6B8AFF",
    header: "#4155D8",
    headerForeground: "#ffffff",
  },
  dark: {
    background: "#10143D",
    foreground: "#FAFAFA",
    card: "#181E49",
    cardForeground: "#FAFAFA",
    popover: "#181E49",
    popoverForeground: "#FAFAFA",
    primary: "#94A6FF",
    primaryForeground: "#10143D",
    secondary: "#1E2850",
    secondaryForeground: "#FAFAFA",
    muted: "#1A2448",
    mutedForeground: "#8B94C1",
    accent: "#1E2850",
    accentForeground: "#FAFAFA",
    destructive: "#E14E4E",
    destructiveForeground: "#FAFAFA",
    border: "#283660",
    input: "#283660",
    ring: "#94A6FF",
    header: "#1F2A7A",
    headerForeground: "#FAFAFA",
  },
};

export const NAV_THEME: Record<"light" | "dark", Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
